### ISSUE TITLE
Limited to one connection at a time

### ISSUE THREAD

**Issue by f-prime** [f-prime/fist#13]
Creating this issue to remind myself that it is an issue and also to create some conversation around this.

The current state of the server only allows for a single client to be connected at a time. So this means that if there are multiple applications that need to access the same Fist instance, one client will have to wait for the other to disconnect before it can start sending commands.

This was just easier to do at first but it will need to be addressed because it's not acceptable.

**Comment by 00-matt** [comment]
Hi, I have started to change `server.c` to use select to allow for multiple 
connections. I'll try and submit a PR tonight, but a few design decisions will 
need to be made, such as deciding when to save the hashmap to disk.

**Comment by f-prime** [comment]
Thank you for opening the PR and taking on this issue. The eventual goal for saving the hashmap to disk would be to have it run periodically in the background asynchronously. Right now I run `sdump` when a client disconnects. For now, a similar system could be adopted but locking of the db file would also have to be implemented. 

Writing to disk will be tricky I think. I'll be around to help so lmk what you are thinking.

**Comment by 00-matt** [comment]
Maybe we could just set an alarm, set some boolean in the signal handler, and 
then handle the saving in the main loop. It should be fine since we would have 
to do something similar to handle signals for exiting cleanly, and for 
handling SIGHUP to reload config in the future if a config is added.

**edit** Implemented this in my PR, needs more testing though.

>Locking of the db file would also have to be implemented.

I think if we stick to a single thread, like Redis does, we'll be able to 
avoid all of that. However it might block clients for a few seconds for larger 
databases.
