### ISSUE TITLE
Why not in C++?

### ISSUE THREAD

**Issue by rishiloyola** [f-prime/fist#3]
Hi,

This might be a stupid way to ask a question on Github but I want to ask you this question. Why did you write it in C and not in C++?

Also I would like to contribute to it. How can I?

**Comment by f-prime** [comment]
Hey @rishiloyola, 

First off, I appreciate your comment and I am also very grateful that you are interested in helping so I hope that what I say doesn't come off as angry or mean. 

I was expecting a comment/issue like this. There was a Hacker News post about this recently that I saw and like clock-work it happened on this project. To answer you question, it's because that's what I chose to do. C++ is a fine language if you use it correctly, I just happen to not like the way it does OOP and I prefer C style code. So why C and not C++? Well, because I wanted to. Will it ever change? No. If you want it written in C++ fork it and rewrite it in C++. 

The language doesn't matter. I often catch myself wondering why I didn't choose Go. Then I have to stop and remind myself that it doesn't really matter. I know C, I was able to develop this relatively quickly in C, I wanted to get my hands dirty writing a big project in C, so I chose C. There is no deeper reason behind it and these kinds of questions are not productive.

I would love for you to help on the project though if you can. Unless you really want to get your hands dirty reading through the code and contributing in that way, I would suggest helping with bugs as there are no doubt many. Download and compile the project then use it, extensively. Try to break it. Use it in some of your own projects. See where it fails and where it shines. That would be the best thing you could do right now for the project and I would be very grateful.

Thanks again for your issue, I hope you get involved.
